package il.cshaifasweng.hsts.entities.enums;

public enum MessageType {
    LOGIN_REQUEST,
    LOGIN_RESPONSE,

    GET_TEACHER_COURSES_REQUEST,
    GET_TEACHER_COURSES_RESPONSE,

    GET_COURSE_QUESTIONS_REQUEST,
    GET_COURSE_QUESTIONS_RESPONSE,

    CREATE_QUESTION_REQUEST,
    CREATE_QUESTION_RESPONSE,
    UPDATE_QUESTION_REQUEST,
    UPDATE_QUESTION_RESPONSE,
    DELETE_QUESTION_REQUEST,
    DELETE_QUESTION_RESPONSE,

    CREATE_MANUAL_EXAM_REQUEST,
    CREATE_MANUAL_EXAM_RESPONSE,

    ERROR
}
